apiVersion: v1
kind: Service
metadata:
  name: {{ include "ride-ops.fullname" . }}
  labels:
    {{- include "ride-ops.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "ride-ops.name" . }}
    release: {{ .Release.Name }}