# monitoring/prometheus-values.yaml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ride-ops:8080']  # Replace with the actual service name and port
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: keep
        regex: themepark-app

  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node

  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: keep
        regex: themepark-app
        source_labels: [__meta_kubernetes_namespace]