spring:
  datasource:
    url: jdbc:mariadb://db:3306/parkdb?useSSL=false&serverTimezone=UTC
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 5000

info:
  app:
    version: CI_PIPELINE_IID
    commit: CI_COMMIT_SHORT_SHA
    branch: CI_COMMIT_BRANCH

management:
  endpoints:
    web:
      exposure:
        include: '*'