# .github/workflows/ci.yaml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_URL }}/ride-ops:${{ github.sha }} ./app/ride-ops

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.REGISTRY_URL }}/ride-ops:${{ github.sha }}

      - name: Update Helm values
        run: |
          sed -i "s/tag: .*/tag: ${{ github.sha }}/" helm/umbrella-chart/values.yaml

      - name: Commit Helm changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add helm/umbrella-chart/values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push

      - name: Trigger ArgoCD sync
        run: |
          argocd app sync themepark-app --auth-token ${{ secrets.ARGOCD_AUTH_TOKEN }}