apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: themepark-app
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
      - name: traefik
        image: traefik:v2.5
        args:
          - "--api.insecure=true"
          - "--providers.kubernetesingress=true"
          - "--entrypoints.web.address=:80"
        ports:
        - name: web
          containerPort: 80
        - name: admin
          containerPort: 8080
        volumeMounts:
        - name: traefik-certificates
          mountPath: /certificates
      volumes:
      - name: traefik-certificates
        secret:
          secretName: traefik-certificates
      serviceAccountName: traefik
      terminationGracePeriodSeconds: 60